# Docker Compose file for the node-bazaar microservice

services:
  # Authentication service
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - 3000:3000
      # - 3001:3001
    volumes:
      - .:/usr/src/app

  # Category service
  category:
    build:
      context: .
      dockerfile: ./apps/category/Dockerfile
      target: development
    command: npm run start:dev category
    env_file:
      - ./apps/category/.env
    ports:
      - 3002:3002
    volumes:
      - .:/usr/src/app

  # Product service
  product:
    build:
      context: .
      dockerfile: ./apps/product/Dockerfile
      target: development
    command: npm run start:dev product
    env_file:
      - ./apps/product/.env
    ports:
      - 3003:3003
      # - 3004:3004
    volumes:
      - .:/usr/src/app

  # Cart service
  cart:
    build:
      context: .
      dockerfile: ./apps/cart/Dockerfile
      target: development
    command: npm run start:dev cart
    env_file:
      - ./apps/cart/.env
    ports:
      - 3005:3005
    volumes:
      - .:/usr/src/app

  # Payments service
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    env_file:
      - ./apps/payments/.env
    ports:
      - 3006:3006
    volumes:
      - .:/usr/src/app

  # Orders service
  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: npm run start:dev orders
    env_file:
      - ./apps/orders/.env
    ports:
      - 3007:3007
    volumes:
      - .:/usr/src/app

  # Reviews service
  reviews:
    build:
      context: .
      dockerfile: ./apps/reviews/Dockerfile
      target: development
    command: npm run start:dev reviews
    env_file:
      - ./apps/reviews/.env
    ports:
      - 3008:3008
    volumes:
      - .:/usr/src/app

  # User service
  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: npm run start:dev user
    env_file:
      - ./apps/user/.env
    ports:
      - 3009:3009
    volumes:
      - .:/usr/src/app

  # Notifications service
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: npm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    ports:
      - 3010:3010
      # - 3011:3011
    volumes:
      - .:/usr/src/app
